apps/base/urls.py
from django.urls import path
from . import views

app_name = "base"

urlpatterns = [
    path("", views.home_page, name="home_page"),
]

apps/contacts/urls.py
from django.urls import path

from . import views

app_name = "contacts"

urlpatterns = [
    path("list/", views.ContactsListView.as_view(), name="contacts_list"),
]

apps/first_example/urls.py
from django.urls import path, include
from . import views

app_name = "first_example"

urlpatterns = [
    path("hi/<name>/<int:age>/", views.GreetingsView.as_view(), name="greetings"),
    path(
        "generate-humans/",
        include(
            [
                path("<int:amount>/", views.generate_humans_view, name="generate_humans_with_amount"),
                path("", views.generate_humans_view, name="generate_humans"),
            ]
        ),
    ),
    path(
        "generate-emails/",
        include(
            [
                path("<int:amount>/", views.generate_users_data_view, name="generate_emails_with_amount"),
                path("", views.generate_users_data_view, name="generate_emails"),
            ]
        ),
    ),
]

core/urls.py
from django.urls import path, include

urlpatterns = [

    path("", include("apps.base.urls")),
    path("", include("apps.first_example.urls")),
    path("contacts/", include("apps.contacts.urls")),

]

apps/contacts/models/contact.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=100)
    phone_number = models.CharField(
        max_length=20,
        blank=True,
        default=0,
        )
    is_auto_generated = models.BooleanField(
        blank=False,
        default=False,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        blank=False,
        null=False,
    )
    modified_at = models.DateTimeField(
        auto_now_add=True,
        blank=False,
        null=False,
    )

    def __str__(self):
        return f"{self.name} {self.phone_number}"

    __repr__ = __str__

apps/contacts/forms.py
from django import forms

from apps.contacts.models import Contact


class GenerateForm(forms.Form):
    amount = forms.IntegerField(
        label="Amount",
        min_value=1,
        max_value=100,
        required=True,
        initial=10,
    )


class ContactSpecialEditForm(forms.ModelForm):
    class Meta:
        model = Contact

        fields = (
            "name",
            "phone_number",
            "is_auto_generated",

        )

apps/base/views.py
import datetime
import random

from django.shortcuts import render


def some_func():
    return "debug123"


def home_page(request):
    now = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M:%S")

    return render(
        request=request,
        template_name="base/home_page.html",
        context={
            "greetings_text": f"Hello, World! Now is {now} in UTC.",
            "nested": {
                "random_number": random.randint(1, 100),
            },
            "title": "Home page",
        },
    )

apps/contacts/views.py
from django.views.generic import ListView

from apps.contacts.models import Contact


class ContactsListView(ListView):
    model = Contact

apps/first_example/views.py
from django.http import HttpResponse


def homework(request):
    return HttpResponse("Hello, Alex!")

apps/first_example/views/generate_humans.py
from django.shortcuts import render

from apps.first_example.services.generate_humans import generate_humans


def generate_humans_view(
    request,
    amount: int = 5,
):
    humans = generate_humans(amount=amount)

    return render(
        request=request,
        template_name="first_example/generate_humans.html",
        context=dict(
            humans=humans,
            title="Humans",
        ),
    )

apps/first_example/views/generate_users_data.py
from django.shortcuts import render
from apps.first_example.services.generate_users_data import generate_users_data


def generate_users_data_view(
    request,
    amount: int = 5,
):
    users = generate_users_data(amount=amount)
    return render(
        request=request,
        template_name="first_example/generate_users_data.html",
        context=dict(
            users=users,
            title="Users",
        ),
    )

apps/first_example/views/greetings.py
from django.views.generic import TemplateView


class GreetingsView(TemplateView):
    template_name = "first_example/greetings.html"

    def get_context_data(self, name: str, age: int, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update(
            name=name,
            age=age,
            #
            title="Greetings",
        )

        return context

apps/templates/_helpers/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            {% if title %}
                {{ title }}
            {% else %}
                Welcome!
            {% endif %}
            | My Website
        {% endblock %}
    </title>
    <style>


        /* Дополнительные стили для header (можно настроить по своему усмотрению) */
        header h1 {
            margin: 0; /* Убираем отступы у заголовка h1 внутри header */
        }
        body {
                background-image: url("https://images.wallpaperscraft.ru/image/single/fon_gradient_volna_207449_3840x2400.jpg");
                background-repeat: no-repeat;
                background-position: center;

                background-attachment: fixed;

                background-size: cover;

                height: 100vh;


                /* Устанавливаем высоту блока body (высота 100%) */
            /* Убираем отступы для body */
            }
    </style>
</head>

<body>

{% include "_helpers/_header.html" %}

<div>
    {% block content %}
        <h1>Hello!</h1>
    {% endblock %}
</div>

</body>
</html>

apps/templates/_helpers/_header.html
<header>
    <div><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1200px-Python-logo-notext.svg.png" alt="Мой логотип" width=100 height=auto></div>


    <ul>
        <li>
            <a href="{% url 'base:home_page' %}">
                Home
            </a>
        </li>
        <li>
            <a href="{% url 'first_example:greetings' name=name|default:'Marina' age=age|default:28 %}">
                Greetings
            </a>
        </li>
        <li>
            <a href="{% url 'first_example:generate_humans' %}">
                Generate humans
            </a>
        </li>
        <li>
            <a href="{% url 'first_example:generate_emails' %}">
                Django HW 11. Templates. Data generators for users.
            </a>
        </li>
        <li>
            <a href="{% url 'contacts:contacts_list' %}">
                Django HW 12. Contacts and commands
            </a>
        </li>
    </ul>
</header>

apps/templates/base/home_page.html
{% extends "_helpers/_base.html" %}


{% block title %}
    {{ title }} :)
{% endblock %}


{% block content %}
    <p>{{ greetings_text }}</p>
    <p><span>Random number: </span><b>{{ nested.random_number }}</b></p>
    <p>{{ debug }}</p>
{% endblock %}

apps/templates/contacts/_contact_list_base.html
<div>
    <a href="{% url 'contacts:contacts_create' %}">
        <button>Create</button>
    </a>
    <a href="{% url 'contacts:contacts_generate' %}">
        <button>Generate new contacts</button>
    </a>
    <a href="{% url 'contacts:contacts_delete' %}">
        <button>Delete contacts</button>
    </a>
</div>
<ol>
    {% for contact in contacts_list %}
        <li>
            <div  style="display:flex; flex-flow: row;">


                    <div style="margin: .2em">
                    <span>{{ contact.pk }}</span>
                    <span> - </span>
                    <span>{{ contact.name }}</span>
                    <span> - </span>
                    <span>{{ contact.phone_number }}</span>
                    <span> - </span>
                    <span>{{ contact.modified_at }}</span>
                    </div>
                    <div style="margin: .2em">
                        <a href="{% url 'contacts:contacts_update' contact.pk %}">
                            <button>Update</button>
                        </a>
                        <a href="{% url 'contacts:contacts_delete' contact.pk %}">
                            <button>Delete</button>
                        </a>
                        <a href="{% url 'contacts:contacts_special_edit' contact.pk %}">
                            <button>Special</button>
                        </a>
                    </div>
            </div>
        </li>
    {% endfor %}
</ol>

apps/templates/contacts/contact_confirm_delete.html
{% extends "_helpers/_base.html" %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }} ?"</p>
        {{ form }}
        <input type="submit" value="Confirm">
    </form>
{% endblock %}

apps/templates/contacts/contact_form.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h1>
        {% if is_update %}
            Update
        {% else %}
            Create
        {% endif %}
        contact
    </h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">
            {% if is_update %}
                Update
             {% else %}
                Create
            {% endif %}
        </button>
    </form>
{% endblock %}

apps/templates/contacts/contact_list.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h1>Contacts</h1>
    <ol>
        {% for contact in object_list %}
            <li>
                <span>{{ contact.pk }}</span>
                <span> - </span>
                <span>{{ contact.name }}</span>
                <span> - </span>
                <span>{{ contact.phone_number }}</span>
                <span> - </span>
                <span>{{ contact.modified_at }}</span>
            </li>
        {% endfor %}
    </ol>
{% endblock %}

apps/templates/contacts/contacts_generate.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h1 style="margin-top: 0;">Animals Generating</h1>

    <form method="POST">
        {% csrf_token %}

        {{ form.as_p}}

        <button type="submit" style="padding: 5px 10px; background-color: #007bff; color: #fff; border: none; border-radius: 3px; cursor: pointer;">Generate</button>
    </form>

    <div style="border-top: 1px solid #ccc; padding-top: 20px; margin-top: 20px;">
        {% include "contacts/_contact_list_base.html" with contacts_list=contacts_list %}
    </div>
{% endblock %}

apps/templates/contacts/contacts_generate__raw_form.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h1 style="margin-top: 0;">Animals Generating</h1>

    <form method="POST">
        {% csrf_token %}
        <label>
            <span>Amount</span>
            <input type="number" name="amount" value="3" style="padding: 5px; border: 1px solid #ccc; border-radius: 3px;" />
        </label>

        <button type="submit" style="padding: 5px 10px; background-color: #007bff; color: #fff; border: none; border-radius: 3px; cursor: pointer;">Generate</button>
    </form>

    <div style="border-top: 1px solid #ccc; padding-top: 20px; margin-top: 20px;">
        {% include "contacts/_contact_list_base.html" with contacts_list=contacts_list %}
    </div>
{% endblock %}

apps/templates/first_example/generate_humans.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h1>Humans</h1>
    <ol>
        {% for human in humans %}
            <li>
                <span>{{ human.name }}</span>
                <span> - </span>
                <span>{{ human.age }}</span>
            </li>
        {% endfor %}
    </ol>
{% endblock %}

apps/templates/first_example/generate_users_data.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h1>Users data</h1>
    <ol>
        {% for user in users %}
            <li>
                Login: {{ user.user_login }}<br>
                Email: {{ user.email }}<br>
                Password: {{ user.password }}<br>
                <p></p>
            </li>
        {% endfor %}
    </ol>
{% endblock %}

apps/templates/first_example/greetings.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <p>Hello, {{ name }}! You are {{ age }} years old!</p>
{% endblock %}

apps/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>